/**
 * ORATOR SKILL CODEX — backend knowledge library.
 *
 * Distilled from the best-skills Top-100 agent-skill rankings
 * (github.com/chrisfbaileycb-arch/best-skills): the database, API, cloud,
 * and engineering-discipline skills that dominate real-world installs —
 * Prisma suite, Supabase/Postgres, Neon, Azure suite, API gateways,
 * TDD, triage, domain modeling, and architecture improvement.
 *
 * Each entry is a compact playbook the forge's 16-expert quorum applies
 * while shaping a blueprint. `skillsForPhase()` maps phases to skills so the
 * right knowledge is "seated" at the right moment of a build.
 */

export interface SkillEntry {
  id: string;
  name: string;
  /** e.g. "database", "api", "cloud", "discipline" */
  domain: "database" | "api" | "cloud" | "discipline";
  source: string;
  /** One-line doctrine. */
  doctrine: string;
  /** Concrete rules the quorum applies. */
  rules: string[];
}

export const SKILL_CODEX: SkillEntry[] = [
  {
    id: "prisma-schema",
    name: "Prisma Schema Craft",
    domain: "database",
    source: "prisma-database-setup + prisma-postgres",
    doctrine: "The schema is the contract — model the domain, not the tables.",
    rules: [
      "One schema.prisma as single source of truth; every model maps to a real domain concept.",
      "Prefer explicit relations with named back-relations; no implicit many-to-many on hot paths.",
      "Enums for closed sets, String[] only when genuinely unbounded.",
      "Indexes declared where queries demand them — never 'just in case'.",
    ],
  },
  {
    id: "prisma-client",
    name: "Type-Safe Data Access",
    domain: "database",
    source: "prisma-client-api + prisma-driver-adapter",
    doctrine: "Every query type-checked at the boundary; no raw strings escaping.",
    rules: [
      "Generate the client in CI; commit nothing generated by hand.",
      "Wrap multi-step writes in interactive transactions with explicit timeouts.",
      "Select only the columns a view renders — no blind findMany() on wide tables.",
      "Singleton client per process; adapters for serverless connection pooling.",
    ],
  },
  {
    id: "postgres-doctrine",
    name: "Postgres Best Practice",
    domain: "database",
    source: "supabase-postgres-best-practices + neon-postgres",
    doctrine: "Relational integrity first; scale reads, never compromise writes.",
    rules: [
      "Row-level security policies on every table a client can reach.",
      "Foreign keys with deliberate ON DELETE behavior — no orphaned rows by accident.",
      "Use generated columns and partial indexes for hot read paths.",
      "Connection budgets: pool at the edge, budget per serverless instance.",
    ],
  },
  {
    id: "api-gateway",
    name: "API Gateway Discipline",
    domain: "api",
    source: "api-gateway",
    doctrine: "Third-party calls cross one guarded threshold, never scattered.",
    rules: [
      "All external calls funnel through a typed gateway module with retries + timeouts.",
      "Rate-limit and cache at the gateway, not at each call site.",
      "Secrets injected per-request from env — never logged, never cached with the response.",
      "Version third-party contracts; pin and monitor for drift.",
    ],
  },
  {
    id: "domain-modeling",
    name: "Domain Modeling",
    domain: "discipline",
    source: "domain-modeling",
    doctrine: "Name the domain precisely and the code writes itself.",
    rules: [
      "Ubiquitous language: entity names mirror the inquest answers verbatim.",
      "Invariants live in the model, not in scattered guards.",
      "Model state transitions explicitly (draft → forged → sealed), never booleans.",
      "One bounded context per module; no leaking across module lines.",
    ],
  },
  {
    id: "tdd",
    name: "Test-Driven Discipline",
    domain: "discipline",
    source: "tdd",
    doctrine: "Red, green, refactor — the forge ships evidence, not hope.",
    rules: [
      "Every contract gets a failing test before implementation.",
      "Tests assert behavior through public seams; no private-state prying.",
      "Fast unit suite (<5s) gates every phase; slow suites gate delivery.",
      "Fixtures over mocks for data shapes; mocks only for true boundaries.",
    ],
  },
  {
    id: "triage",
    name: "Triage & Incidents",
    domain: "discipline",
    source: "triage",
    doctrine: "Every failure classifies, routes, and teaches.",
    rules: [
      "Severity ladder agreed up front: P0 blocks delivery, P2 ships with a ticket.",
      "Reproduce before fix; a fix without a repro is a hypothesis.",
      "Each incident appends a regression test to the suite.",
      "Blameless postmortems sealed into the build dossier.",
    ],
  },
  {
    id: "architecture",
    name: "Architecture Improvement",
    domain: "discipline",
    source: "improve-codebase-architecture",
    doctrine: "Refactor on contact — every phase leaves the shape better.",
    rules: [
      "Detect cyclic imports and dead exports before adding features.",
      "Extract repeated patterns only on the third occurrence.",
      "Module boundaries enforced by import-lint, not convention.",
      "Complexity budget per file; split before it compounds.",
    ],
  },
  {
    id: "cloud-doctrine",
    name: "Cloud Deployment Doctrine",
    domain: "cloud",
    source: "azure-deploy + azure-validate",
    doctrine: "Validate before deploy; deploy is the smallest, most boring step.",
    rules: [
      "Pre-deploy validation gates: types, lint, tests, secret scan — all green.",
      "Infrastructure declared as config; no console drift.",
      "Preview environments per branch; production promoted, never pushed.",
      "Rollback is a first-class path, rehearsed before it is needed.",
    ],
  },
  {
    id: "observability",
    name: "Instrumentation & Insight",
    domain: "cloud",
    source: "appinsights-instrumentation",
    doctrine: "You cannot direct what you cannot see.",
    rules: [
      "Structured events at every phase boundary of the request lifecycle.",
      "Correlation IDs thread client → gateway → worker.",
      "Dashboards watch the four golden signals: latency, traffic, errors, saturation.",
      "Alerts page on symptoms (user impact), never on causes.",
    ],
  },
];

/** Skills seated for a given forge phase keyword (id matching plan phases). */
export function skillsForPhase(phaseId: string): SkillEntry[] {
  const map: Record<string, string[]> = {
    genesis: ["domain-modeling"],
    architecture: ["domain-modeling", "architecture"],
    schema: ["prisma-schema", "postgres-doctrine"],
    backend: ["prisma-client", "api-gateway", "tdd"],
    frontend: ["architecture", "tdd"],
    review: ["architecture", "triage"],
    audit: ["tdd", "triage"],
    deploy: ["cloud-doctrine", "observability"],
  };
  const key = phaseId.toLowerCase();
  const ids = Object.entries(map).find(([k]) => key.includes(k))?.[1] ?? [];
  return SKILL_CODEX.filter((s) => ids.includes(s.id));
}

/** Compact journal line for the build log. */
export function skillJournalLine(skill: SkillEntry): string {
  return `codex · ${skill.name} — ${skill.doctrine}`;
}
